Site 0/Site 0/Models/ErrorViewModel.cs
namespace Site_0.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Site 0/Site 0/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Site_0.Models;

namespace Site_0.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Site 0/Site 0/Controllers/TesteController.cs
using Microsoft.AspNetCore.Mvc;

namespace Site_0.Controllers;

public class Result
{
    public string Texto = string.Empty;
    public string Cifra = string.Empty;
}

public class TesteController : Controller
{
    private readonly ILogger<TesteController> _logger;
    public TesteController(
        ILogger<TesteController> logger 
    )
    {
        _logger = logger;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View("Index", new Result());
    }

    [HttpPost]
    public IActionResult Index(string texto, string cifra)
    {
        Result resultado = new();
        if(!string.IsNullOrEmpty(texto)) resultado.Texto = texto.ToUpper();
        if(!string.IsNullOrEmpty(cifra)) resultado.Cifra = cifra.ToUpper();

        return View("Index", resultado);
    }
}

Site 0/Site 0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site_0</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Site_0.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Site_0</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Site_0 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Site 0/Site 0/Views/Teste/Index.cshtml
@model Site_0.Controllers.Result;

@{
    <h1>manandaiwnd</h1>
}

<h1>CONTROLLER: Teste</h1>
<h2>Método Index</h2>
<h3>View Index</h3>

<hr />

<form method="post" 
asp-action="Index" 
asp-controller="Teste">

    <input type="text" id="texto" name="texto" placeholder="Palavra"/>
    <input type="text" id="cifra" name="cifra" placeholder="Cifra"/>
    <input type="number" id="numero" name="numero" />
    <button type="submit">Enviar</button>

</form>

<hr />

@if (!string.IsNullOrEmpty(Model.Texto) || !string.IsNullOrEmpty(Model.Cifra))
{
    string cipher = string.Empty;
    int cipherKey = 2;

    // Conversão de texto para cifra

    foreach (char x in Model.Texto)
    {
        int sum = x + cipherKey;
        /*

        65 A
            90 Z

        */

        if (sum > 90)
        {
            cipher += (char)(65 - (91 - x) + cipherKey);
        }
        else cipher += (char)(x + cipherKey);
    }

    // Conversão de cifra para texto

    foreach (char x in Model.Cifra)
    {
        int sum = x - cipherKey;

        if (sum < 65)
        {
            cipher += (char)(90 + (x - 64) - cipherKey);
        }
        else cipher += (char)(x - cipherKey);
    }

    <div>
        <p>Texto: @Model.Texto</p>
        <p>Cifra: @Model.Cifra</p>
        <p>Conversão: @cipher</p>
    </div>
}

Site 0/Site 0/Views/Teste/Teste.cshtml
@{
}

<h1>CONTROLLER: Teste</h1>
<h2>Método Index</h2>
<h3>View Teste</h3>