05ClassesEntidades/05ClassesEntidades/Controllers/CustomerController.cs
using Modelo; // Não é a melhor alternativa, mas para poupar tepo, utilizaremos esta
using Repository;
using Microsoft.AspNetCore.Mvc;

namespace _05ClassesEntidades.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IWebHostEnvironment environment;

        private CustomerRepository _customerRepository;

        public CustomerController(IWebHostEnvironment environment)
        {
            _customerRepository = new CustomerRepository();
            this.environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Customer> customers = _customerRepository.RetrieveAll();
            return View(customers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }   

        [HttpPost]
        public IActionResult Create(Customer c)
        {
            _customerRepository.Save(c);

            List<Customer> customers = _customerRepository.RetrieveAll();

            return View("Index", customers);

            // return View();
            // Se nenhum valor for especificado, ele voltará para o método que o chamou (Create)
        }


        [HttpGet]
        public IActionResult ExportDelimitatedFile()
        {
            string fileContent = string.Empty;
            foreach (Customer c in CustomerData.Customers)
            {
                fileContent +=
                    @$"{c.Id};
                       {c.Name!};
                       {c.HomeAddress!.Id};
                       {c.HomeAddress!.City};
                       {c.HomeAddress!.StateOrProvince};
                       {c.HomeAddress!.Country};
                       {c.HomeAddress!.StreetLine1};
                       {c.HomeAddress!.StreetLine2};
                       {c.HomeAddress!.PostalCode};
                       {c.HomeAddress!.AddressType};
                       \n
                    ";
            }

            SaveFile(fileContent, "DelimitatedFile.txt");

            return View();
        }

        [HttpGet]
        public IActionResult ExportFixedFile()
        {
            string fileContent = string.Empty;
            foreach (Customer c in CustomerData.Customers)
            {
                fileContent +=
                    String.Format("{0:5}", c.Id) +
                    String.Format("{0:64}", c.Name) +
                    String.Format("{0:5}", c.HomeAddress!.Id) +
                    String.Format("{0:32}", c.HomeAddress!.City) +
                    String.Format("{0:2}", c.HomeAddress!.StateOrProvince) +
                    String.Format("{0:32}", c.HomeAddress!.Country) +
                    String.Format("{0:64}", c.HomeAddress!.StreetLine1) +
                    String.Format("{0:64}", c.HomeAddress!.StreetLine2) +
                    String.Format("{0:9}", c.HomeAddress!.PostalCode) +
                    String.Format("{0:16}", c.HomeAddress!.AddressType)
                ;

                fileContent +=
                    @$"{c.Id};
                       {c.Name};
                       {c.HomeAddress!.Id};
                       {c.HomeAddress.City};
                       {c.HomeAddress.StateOrProvince};
                       {c.HomeAddress.Country};
                       {c.HomeAddress.StreetLine1};
                       {c.HomeAddress.StreetLine2};
                       {c.HomeAddress.PostalCode};
                       {c.HomeAddress.AddressType};
                    ";
            }

            SaveFile(fileContent, "FixedFile.txt");

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int? id) 
        {
            if (id is null || id.Value <= 0)
                return NotFound();

            Customer customer =
            _customerRepository.Retrieve(id.Value);

            if (customer == null)
                return NotFound();

            return View(customer);
        }     

        [HttpPost]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id is null || id.Value <= 0)
                return NotFound();

            if (!_customerRepository.DeleteById(id.Value))
                return NotFound();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id is null || id.Value <= 0)
                return NotFound();

            Customer customer =
            _customerRepository.Retrieve(id.Value);

            if (customer == null)
                return NotFound();

            return View(customer);
        }

        public IActionResult ConfirmUpdate(Customer newCustomer)
        {
            if (newCustomer.Id <= 0)
                return NotFound();

            _customerRepository.Update(newCustomer);

            return RedirectToAction("Index");
        }

        private bool SaveFile(string content, string fileName)
        {
            bool ret = true;

            if (string.IsNullOrEmpty(content) || string.IsNullOrEmpty(fileName))
                return false;

            var path = Path.Combine(environment.WebRootPath, "TextFiles");

            try
            {
                if (!System.IO.Directory.Exists(path))
                    System.IO.Directory.CreateDirectory(path);

                var filepath = Path.Combine(
                    path,
                    fileName
                );

                using StreamWriter sw = System.IO.File.CreateText(filepath);
                sw.Write(content);
            }
            catch (IOException ioEx)
            {
                string msg = ioEx.Message;
                ret = false;
                //throw ioEx;
            }
            catch (Exception ex)
            {
                string msg = ex.Message;
                ret = false;
            }

            return ret;

        }
    }
}

05ClassesEntidades/05ClassesEntidades/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Repository;
using _05ClassesEntidades.ViewModels;
using Modelo;

namespace _05ClassesEntidades.Controllers
{
    public class OrderController : Controller
    {
        private readonly IWebHostEnvironment environment;
        private readonly OrderRepository _orderRepository;
        private readonly CustomerRepository _customerRepository;
        private readonly ProductRepository _productRepository;

        public OrderController(IWebHostEnvironment environment)
        {
            this.environment = environment;
            _orderRepository = new OrderRepository();
            _customerRepository = new CustomerRepository();
            _productRepository = new ProductRepository();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_orderRepository.RetrieveAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            List<SelectedItem> items = [];
            OrderViewModel viewModel = new();
            viewModel.Customers = _customerRepository.RetrieveAll();
            var products = _productRepository.RetrieveAll();

            foreach (var product in products)
            {
                items.Add(new SelectedItem() {
                    OrderItem = new() { Product = product } 
                }); 
            }
            viewModel.SelectedItems = items;

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(OrderViewModel model)
        {
            Order order = new()
            {
                Customer = _customerRepository.Retrieve(model.CustomerId!.Value),
                OrderDate = DateTime.Now
            };

            int count = 1;
            foreach (var item in model.SelectedItems!)
            {
                if (item.IsSelected)
                {
                    order.OrderItems!.Add(
                        new OrderItem()
                        {
                            Id = count,
                            Product = _productRepository.Retrieve(item.OrderItem.Product!.Id),
                            Quantity = item.OrderItem.Quantity,
                            PurchasePrice = item.OrderItem.PurchasePrice
                        }
                    );

                    count++;
                }
            }

            _orderRepository.Save(order);

            return RedirectToAction("Index");
        }
    }
}

05ClassesEntidades/05ClassesEntidades/Controllers/ProductController.cs
using Modelo; // Não é a melhor alternativa, mas para poupar tepo, utilizaremos esta
using Repository;
using Microsoft.AspNetCore.Mvc;

namespace _05ClassesEntidades.Controllers
{
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment environment;

        private ProductRepository _productRepository;

        public ProductController(IWebHostEnvironment environment)
        {
            _productRepository = new ProductRepository();
            this.environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Product> products = _productRepository.RetrieveAll();
            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product p)
        {
            _productRepository.Save(p);

            List<Product> products = _productRepository.RetrieveAll();

            return View("Index", products);

            // return View();
            // Se nenhum valor for especificado, ele voltará para o método que o chamou (Create)
        }

        [HttpGet]
        public IActionResult ExportDelimitatedFile()
        {
            string fileContent = string.Empty;
            foreach (Product p in CustomerData.Products)
            {
                fileContent +=
                       $"{p.Id};\n{p.ProductName};\n{p.Description};\n{p.CurrentPrice}\n\n";
            }

            var path = Path.Combine(
                environment.WebRootPath,
                "TextFiles"
            );

            if (!System.IO.Directory.Exists(path))
                System.IO.Directory.CreateDirectory(path);

            var filepath = Path.Combine(
                path,
                "Produtos.txt"
            );

            if (!System.IO.File.Exists(filepath))
            {
                using StreamWriter sw = System.IO.File.CreateText(filepath);
                sw.Write(fileContent);
            }

            return View();
        }
    }
}

05ClassesEntidades/05ClassesEntidades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _05ClassesEntidades</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_05ClassesEntidades.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_05ClassesEntidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Create">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - _05ClassesEntidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>